### ISSUE TITLE
8/17 レビュー

### ISSUE THREAD

**Issue by shu-illy** [shu-illy/qin-team-pf#11]

**Comment by takeyu1013** [comment]
外部ライブラリを活用していて、型定義を含めたディレクトリ構成もきれいなので、言うべきことが思いつかないのですが、申し訳程度にコメントさせていただきます！
[![LGTMeow](https://lgtm-images.lgtmeow.com/2021/03/16/22/5863a89c-4d4e-4f00-bf08-f1ed45cd23cb.webp)](https://lgtmeow.com)

## `Layout`コンポーネントについて
コーディングの方針によると思いますが、省略するのもありかもです。

```diff
- <Layout showTitleArea={true}>
+ <Layout showTitleArea>
```
https://zenn.dev/nownewnao/articles/a3045cb7954d67

## `BlogPage`及び`PortfolioPage`コンポーネントについて
杞憂だったらすみませんが、エラーの時に`Layout`コンポーネントがないのは意図的にそうしている（`Header`など、メニューごとなくなってしまう？）感じでしょうか？
早期リターンしているのは見やすくてよいと思いました！

**Comment by kosu27** [comment]
コンポーネント分割をAtomic Designを使い綺麗なディレクトリ構成だと感じました。
自分はmoleculesとorganismsの区別がいまいち理解できていないので、参考にさせていただきます🙇‍♂️

**Comment by kosu27** [comment]
自分の知見がとても少なく指摘する部分が見つかりませんでした😓
お力になれず申し訳ありません...
全体的にとても可読性のある綺麗な構成でコードを書かれていて、めちゃくちゃ学びになりました！
![LGTM](https://image.lgtmoon.dev/178018)

**Comment by shu-illy** [comment]
@takeyu1013 
> コーディングの方針によると思いますが、省略するのもありかもです。

この書き方知りませんでした！
ありがとうございます🙏

> 杞憂だったらすみませんが、エラーの時にLayoutコンポーネントがないのは意図的にそうしている（Headerなど、メニューごとなくなってしまう？）感じでしょうか？

404とかのエラーページのことですかね？
であれば特に考慮してませんでした😅
が、まあNext.jsデフォルトのエラーページで十分かなと思いました！
